name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx
          cache: 'gradle'

      - name: Build and check with Gradle
        run: ./gradlew --no-daemon check

      - name: Build fat jar
        run: ./gradlew --no-daemon shadowJar

      - name: Generate Javadoc
        run: ./gradlew --no-daemon javadoc

      - name: Upload fat jar
        uses: actions/upload-artifact@v4
        with:
          name: tobtahc-jar-${{ runner.os }}
          path: build/libs/*.jar
          if-no-files-found: error

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: tobtahc-javadoc-${{ runner.os }}
          path: build/docs/javadoc/**
          if-no-files-found: error
